SELECT TE.ID_CAMPAIGN idCampaign, C.NAME nameCampaign, C.ID_OSC idOSC, O.DESCRIPTION descriptionOSC
        FROM TEAM_EMPLOYEES TE
        JOIN CAMPAIGNS C ON C.ID = TE.ID_CAMPAIGN
        JOIN OSC O ON O.ID = C.ID_OSC
        WHERE 1 = 1
        AND TE.ID_EMPLOYEE = 1
        AND TE.FINAL_DATE IS NULL