SELECT (SELECT COUNT (D.ID) FROM DONATIONS D WHERE D.ID_EMPLOYEE_TEAM = E.ID) TOTALDONATIONS,
(SELECT SUM (D.AMOUNT) FROM DONATIONS D WHERE D.ID_EMPLOYEE_TEAM = E.ID) TOTALAMOUNTDONATIONS,
(SELECT COUNT (D.ID_TYPE_PAY) FROM DONATIONS D WHERE D.ID_EMPLOYEE_TEAM = E.ID AND D.ID_TYPE_PAY =1) CREDITTYPE,
(SELECT SUM (DR.PRODUCTIVE_HOURS) FROM DAILY_RECORDS DR WHERE DR.ID_EMPLOYEE_TEAM = E.ID)TOTALPRODUCTIVEHOURS,
(SELECT SUM (DR.NON_PRODUCTIVE_HOURS) FROM DAILY_RECORDS DR WHERE DR.ID_EMPLOYEE_TEAM = E.ID)TOTALNONPRODUCTIVEHOURS
FROM EMPLOYEES E WHERE E.ID = 1

