CREATE TABLE EMPLOYEE_TYPES
(
<<<<<<< HEAD
  ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
  TYPE_EMPLOYEE VARCHAR (20)
=======
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	TYPE_EMPLOYEE VARCHAR (20)
>>>>>>> d9cc07b206ae3cbfa33e7f02f3727fa116a13d58
);

CREATE TABLE OSC
(
<<<<<<< HEAD
  ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
  DESCRIPTION VARCHAR (100)
=======
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR (100)
>>>>>>> d9cc07b206ae3cbfa33e7f02f3727fa116a13d58
);

CREATE TABLE LOCATIONS
(
<<<<<<< HEAD
  ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
  DESCRIPTION VARCHAR (30)
=======
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR (30)
>>>>>>> d9cc07b206ae3cbfa33e7f02f3727fa116a13d58
);

CREATE TABLE CAMPAIGN_TYPES
(
<<<<<<< HEAD
  ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
  DESCRIPTION VARCHAR (30)
=======
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR (30)
>>>>>>> d9cc07b206ae3cbfa33e7f02f3727fa116a13d58
);

CREATE TABLE CAMPAIGNS
(
<<<<<<< HEAD
  ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
  NAME VARCHAR (30),
  ID_LOC INT,
  ID_OSC INT,
  ID_TYPE_CAMPAIGN INT
=======
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	NAME VARCHAR (30),
	ID_LOC INT,
	ID_OSC INT,
	ID_TYPE_CAMPAIGN INT
>>>>>>> d9cc07b206ae3cbfa33e7f02f3727fa116a13d58
);

CREATE TABLE EMPLOYEES
(
<<<<<<< HEAD
  ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
  NAME VARCHAR (20),
  LASTNAME VARCHAR (20),
  ID_TYPE_EMPLOYEE INT,
  NICKNAME NVARCHAR(20),
  PASSWORD NVARCHAR (15)
=======
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	NAME VARCHAR (20),
	LASTNAME VARCHAR (20),
	ID_TYPE_EMPLOYEE INT,
	NICKNAME NVARCHAR(20),
	PASSWORD NVARCHAR (15)
>>>>>>> d9cc07b206ae3cbfa33e7f02f3727fa116a13d58
);

CREATE TABLE TEAM_EMPLOYEES
(
<<<<<<< HEAD
  ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
  ID_EMPLOYEE INT,
  INITIAL_DATE DATETIME,
  FINAL_DATE DATETIME,
  ID_CAMPAIGN INT
=======
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	ID_EMPLOYEE INT,
	INITIAL_DATE DATETIME,
	FINAL_DATE DATETIME,
	ID_CAMPAIGN INT
>>>>>>> d9cc07b206ae3cbfa33e7f02f3727fa116a13d58
);

CREATE TABLE PAY_TYPES
(
<<<<<<< HEAD
  ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
  DESCRIPTION VARCHAR (10)
=======
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR (10)
);

CREATE TABLE DONORS 
(
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	DNI VARCHAR2(10) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	LASTNAME VARCHAR2(20),
	AGE NUMERIC(2),
	CONSTRAINT DNI_UNIQUE UNIQUE (DNI)
>>>>>>> d9cc07b206ae3cbfa33e7f02f3727fa116a13d58
);

CREATE TABLE DONATIONS
(
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	AMOUNT FLOAT,
	ID_TYPE_PAY INT,
	ID_EMPLOYEE_TEAM INT,
	ID_CAMPAIGN INT,
<<<<<<< HEAD
	DNI VARCHAR2(10) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	LASTNAME VARCHAR2(20),
	AGE NUMERIC(2),
  GENDER VARCHAR2(1),
=======
	ID_DONOR INT,
>>>>>>> d9cc07b206ae3cbfa33e7f02f3727fa116a13d58
	CREATE_DATE DATETIME
);

CREATE TABLE DAILY_RECORDS
(
<<<<<<< HEAD
  ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
  ID_EMPLOYEE_TEAM INT,
  ID_CAMPAIGN INT,
  PRODUCTIVE_HOURS FLOAT,
  NON_PRODUCTIVE_HOURS FLOAT,
  CREATE_DATE DATETIME
=======
	ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
	ID_EMPLOYEE_TEAM INT,
	ID_CAMPAIGN INT,
	PRODUCTIVE_HOURS FLOAT,
	NON_PRODUCTIVE_HOURS FLOAT,
	CREATE_DATE DATETIME
>>>>>>> d9cc07b206ae3cbfa33e7f02f3727fa116a13d58
);

ALTER TABLE CAMPAIGNS
ADD FOREIGN KEY (ID_LOC) REFERENCES LOCATIONS;
ALTER TABLE CAMPAIGNS
ADD FOREIGN KEY (ID_OSC) REFERENCES OSC;
ALTER TABLE CAMPAIGNS
ADD FOREIGN KEY (ID_TYPE_CAMPAIGN) REFERENCES CAMPAIGN_TYPES;

ALTER TABLE EMPLOYEES
ADD FOREIGN KEY (ID_TYPE_EMPLOYEE) REFERENCES EMPLOYEE_TYPES;

ALTER TABLE TEAM_EMPLOYEES
ADD FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEES;
ALTER TABLE TEAM_EMPLOYEES
ADD FOREIGN KEY (ID_CAMPAIGN) REFERENCES CAMPAIGNS;

ALTER TABLE DONATIONS
ADD FOREIGN KEY (ID_TYPE_PAY) REFERENCES PAY_TYPES;
ALTER TABLE DONATIONS
ADD FOREIGN KEY (ID_EMPLOYEE_TEAM) REFERENCES TEAM_EMPLOYEES;
ALTER TABLE DONATIONS
ADD FOREIGN KEY (ID_CAMPAIGN) REFERENCES CAMPAIGNS;
ALTER TABLE DONATIONS
ADD FOREIGN KEY (ID_DONOR) REFERENCES DONORS;

ALTER TABLE DAILY_RECORDS
ADD FOREIGN KEY (ID_EMPLOYEE_TEAM) REFERENCES TEAM_EMPLOYEES;
ALTER TABLE DAILY_RECORDS
ADD FOREIGN KEY (ID_CAMPAIGN) REFERENCES CAMPAIGNS;
