SELECT E.ID, E.NAME, E.LASTNAME,
  (SELECT COUNT (D.ID)
    FROM DONATIONS D
    WHERE D.ID_CAMPAIGN = TE.ID_CAMPAIGN
    AND D.ID_EMPLOYEE_TEAM = E.ID) TOTALDONATIONS,
  (SELECT SUM (D.AMOUNT)
    FROM DONATIONS D
    WHERE D.ID_CAMPAIGN = TE.ID_CAMPAIGN
    AND D.ID_EMPLOYEE_TEAM = E.ID) TOTALAMOUNTDONATIONS,
  (SELECT SUM (DR.PRODUCTIVE_HOURS)
    FROM DAILY_RECORDS DR
    WHERE DR.ID_CAMPAIGN = TE.ID_CAMPAIGN
    AND DR.ID_EMPLOYEE_TEAM = E.ID) TOTALPRODUCTIVEHOURS,
  (SELECT SUM (DR.NON_PRODUCTIVE_HOURS)
    FROM DAILY_RECORDS DR
    WHERE DR.ID_CAMPAIGN = TE.ID_CAMPAIGN
    AND DR.ID_EMPLOYEE_TEAM = E.ID) TOTALNONPRODUCTIVEHOURS,
  TE.INITIAL_DATE INITIALDATE,
  TE.FINAL_DATE FINALDATE
FROM EMPLOYEES E
JOIN TEAM_EMPLOYEES TE ON TE.ID_EMPLOYEE = E.ID
WHERE TE.ID_CAMPAIGN = 1
