-- LOGIN
--PARAM: NICKNAME Y PASSWORD

SELECT E.ID, E.NAME, E.LASTNAME
, (SELECT T.ID_TYPE_EMPLOYEE FROM TEAMS T 
	WHERE 1 = 1
	AND T.FINAL_DATE IS NULL 
	AND T.STATUS IS TRUE 
	AND T.ID_EMPLOYEE = E.ID ) AS IDTYPE
, (SELECT T.ID_CAMPAIGN FROM TEAMS T 
	WHERE 1 = 1
	AND T.FINAL_DATE IS NULL 
	AND T.STATUS IS TRUE 
	AND T.ID_EMPLOYEE = E.ID) AS IDCAMPAIGN
FROM EMPLOYEES E
WHERE E.NICKNAME LIKE 'JMARK' AND E.PASSWORD LIKE '123'