-- LOGIN
--PARAM: NICKNAME Y PASSWORD

SELECT E.ID, E.NAME, E.LASTNAME, TE.ID_TYPE_EMPLOYEE, TE.ID_CAMPAIGN
FROM TEAMS TE JOIN EMPLOYEES E ON E.ID = TE.ID_EMPLOYEE
WHERE 1 = 1
AND TE.FINAL_DATE IS NULL 
AND TE.STATUS IS TRUE 
AND TE.ID_EMPLOYEE = (SELECT E1.ID FROM EMPLOYEES E1 WHERE E1.NICKNAME LIKE 'JMARK' AND E1.PASSWORD LIKE '123')